# Generated by Django 5.2.3 on 2025-06-25 10:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attendee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('instrument', models.CharField(choices=[('S1', 'Soprano'), ('MS', 'Mezzo-Soprano'), ('A1', 'Higher-Alto'), ('A2', 'Lower-Alto'), ('CA', 'Contra-Alto'), ('CT', 'Counter-Tenor'), ('T1', 'Higher-Tenor'), ('T2', 'Lower-Tenor'), ('B1', 'Baritone'), ('B2', 'Bass'), ('CB', 'Contra-Bass')], max_length=2)),
                ('is_active', models.BooleanField(default=True)),
                ('expert_level', models.CharField(choices=[('1', 'Beginner'), ('2', 'Enthusiast'), ('3', 'Experienced'), ('4', 'Schooled'), ('5', 'Professional')], max_length=1)),
                ('phone_number', models.CharField(blank=True, max_length=17)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('address', models.CharField(blank=True, max_length=250)),
                ('date_of_birth', models.DateField(verbose_name='birthday')),
                ('messenger', models.CharField(blank=True, max_length=250)),
                ('shirt_size', models.CharField(choices=[('XXS', '2x Extra Small'), ('XS', 'Extra Small'), ('S', 'Small'), ('M', 'Medium'), ('L', 'Large'), ('XL', 'Extra Large'), ('XXL', '2x Extra Large'), ('XXXL', '3x Extra Large')], max_length=4)),
                ('additional_attendee_notes', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='RehearsalDates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rehearsal_subtitle', models.CharField(max_length=250)),
                ('rehearsal_location', models.CharField(max_length=250)),
                ('rehearsal_calendar_specific', models.DateField(verbose_name='rehearsal specific date')),
                ('additional_rehearsal_notes', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Songs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('composer', models.CharField(max_length=250)),
                ('author', models.CharField(max_length=250)),
                ('genre', models.CharField(max_length=250)),
                ('number_of_copies', models.CharField(max_length=4)),
                ('number_of_pages', models.CharField(max_length=4)),
                ('number_of_voices', models.CharField(max_length=4)),
                ('difficulty_level', models.CharField(choices=[('1', 'Beginner'), ('2', 'Enthusiast'), ('3', 'Experienced'), ('4', 'Schooled'), ('5', 'Professional')], max_length=1)),
                ('transcript', models.TextField()),
                ('translation', models.TextField()),
                ('speech_articulation', models.TextField()),
                ('date_of_concert', models.DateField(verbose_name='date of concert')),
                ('additional_songs_notes', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='CurrentRehearsal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attendance', models.IntegerField(choices=[(1, 'present'), (2, 'absent'), (3, 'late')])),
                ('attendee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='secondapp.attendee')),
                ('date_of_rehearsal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='secondapp.rehearsaldates')),
                ('songs', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='secondapp.songs')),
            ],
        ),
    ]
