# Generated by Django 5.2.3 on 2025-06-26 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secondapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='songs',
            old_name='author',
            new_name='song_author',
        ),
        migrations.RenameField(
            model_name='songs',
            old_name='composer',
            new_name='song_composer',
        ),
        migrations.RenameField(
            model_name='songs',
            old_name='difficulty_level',
            new_name='song_difficulty_level',
        ),
        migrations.RenameField(
            model_name='songs',
            old_name='genre',
            new_name='song_genre',
        ),
        migrations.RenameField(
            model_name='songs',
            old_name='title',
            new_name='song_title',
        ),
        migrations.AlterField(
            model_name='attendee',
            name='additional_attendee_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='rehearsaldates',
            name='additional_rehearsal_notes',
            field=models.TextField(blank=True),
        ),
    ]
