# Generated by Django 5.2.4 on 2025-07-18 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secondapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arranger',
            name='tags',
            field=models.ManyToManyField(blank=True, to='secondapp.tag'),
        ),
        migrations.AlterField(
            model_name='composer',
            name='tags',
            field=models.ManyToManyField(blank=True, to='secondapp.tag'),
        ),
        migrations.AlterField(
            model_name='musician',
            name='tags',
            field=models.ManyToManyField(blank=True, to='secondapp.tag'),
        ),
        migrations.AlterField(
            model_name='poet',
            name='tags',
            field=models.ManyToManyField(blank=True, to='secondapp.tag'),
        ),
        migrations.AlterField(
            model_name='rehearsal',
            name='tags',
            field=models.ManyToManyField(blank=True, to='secondapp.tag'),
        ),
        migrations.AlterField(
            model_name='singer',
            name='tags',
            field=models.ManyToManyField(blank=True, to='secondapp.tag'),
        ),
        migrations.AlterField(
            model_name='song',
            name='tags',
            field=models.ManyToManyField(blank=True, to='secondapp.tag'),
        ),
    ]
