# Generated by Django 5.2.4 on 2025-08-05 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secondapp', '0002_alter_arranger_tags_alter_composer_tags_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='genre',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='arranger',
            name='tags',
            field=models.ManyToManyField(blank=True, help_text='max singers 5, others 3', to='secondapp.tag'),
        ),
        migrations.AlterField(
            model_name='composer',
            name='tags',
            field=models.ManyToManyField(blank=True, help_text='max singers 5, others 3', to='secondapp.tag'),
        ),
        migrations.AlterField(
            model_name='musician',
            name='tags',
            field=models.ManyToManyField(blank=True, help_text='max singers 5, others 3', to='secondapp.tag'),
        ),
        migrations.AlterField(
            model_name='poet',
            name='tags',
            field=models.ManyToManyField(blank=True, help_text='max singers 5, others 3', to='secondapp.tag'),
        ),
        migrations.AlterField(
            model_name='rehearsal',
            name='tags',
            field=models.ManyToManyField(blank=True, help_text='max 5', to='secondapp.tag'),
        ),
        migrations.AlterField(
            model_name='singer',
            name='tags',
            field=models.ManyToManyField(blank=True, help_text='max singers 5, others 3', to='secondapp.tag'),
        ),
        migrations.AlterField(
            model_name='song',
            name='tags',
            field=models.ManyToManyField(blank=True, help_text='max 3', to='secondapp.tag'),
        ),
    ]
