# Generated by Django 5.2.4 on 2025-08-05 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secondapp', '0003_song_genre_alter_arranger_tags_alter_composer_tags_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='genre',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
