# Generated by Django 5.2.4 on 2025-08-05 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secondapp', '0004_alter_song_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='composer',
            name='musical_era',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
