# Generated by Django 5.2.4 on 2025-08-13 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secondapp', '0005_alter_composer_musical_era'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='date_added',
            field=models.DateField(auto_now=True),
        ),
    ]
