# Generated by Django 5.2.4 on 2025-08-14 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secondapp', '0006_tag_date_added'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='date_added',
            field=models.DateField(auto_now_add=True),
        ),
    ]
