# Generated by Django 5.2.5 on 2025-08-17 19:28

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secondapp', '0007_alter_tag_date_added'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rehearsal',
            options={'verbose_name_plural': 'Rehearsals'},
        ),
        migrations.AddField(
            model_name='rehearsal',
            name='attendance_count',
            field=models.PositiveIntegerField(default=0, help_text='Actual attendance count'),
        ),
        migrations.AddField(
            model_name='rehearsal',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rehearsal',
            name='duration_minutes',
            field=models.PositiveIntegerField(blank=True, help_text='Expected duration in minutes', null=True),
        ),
        migrations.AddField(
            model_name='rehearsal',
            name='is_cancelled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rehearsal',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='song',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='song',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='tag',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tag',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='rehearsal',
            name='singers',
            field=models.ManyToManyField(blank=True, to='secondapp.singer'),
        ),
        migrations.AlterField(
            model_name='rehearsal',
            name='songs',
            field=models.ManyToManyField(blank=True, to='secondapp.song'),
        ),
        migrations.AlterField(
            model_name='song',
            name='arranger',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='songs', to='secondapp.arranger'),
        ),
        migrations.AlterField(
            model_name='song',
            name='composer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='songs', to='secondapp.composer'),
        ),
        migrations.AlterField(
            model_name='song',
            name='poet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='songs', to='secondapp.poet'),
        ),
    ]
