# Generated by Django 5.2.5 on 2025-08-18 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secondapp', '0008_alter_rehearsal_options_rehearsal_attendance_count_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='arranger',
            options={'ordering': ['last_name', 'first_name'], 'verbose_name': 'Arranger', 'verbose_name_plural': 'Arrangers'},
        ),
        migrations.AlterModelOptions(
            name='composer',
            options={'ordering': ['last_name', 'first_name'], 'verbose_name': 'Composer', 'verbose_name_plural': 'Composers'},
        ),
        migrations.AlterModelOptions(
            name='musician',
            options={'ordering': ['last_name', 'first_name'], 'verbose_name': 'Musician', 'verbose_name_plural': 'Musicians'},
        ),
        migrations.AlterModelOptions(
            name='poet',
            options={'ordering': ['last_name', 'first_name'], 'verbose_name': 'Poet', 'verbose_name_plural': 'Poets'},
        ),
        migrations.AlterModelOptions(
            name='rehearsal',
            options={'ordering': ['-calendar'], 'verbose_name_plural': 'Rehearsals'},
        ),
        migrations.AlterModelOptions(
            name='singer',
            options={'ordering': ['voice', 'last_name'], 'verbose_name': 'Singer', 'verbose_name_plural': 'Singers'},
        ),
        migrations.AlterModelOptions(
            name='song',
            options={'ordering': ['title']},
        ),
        migrations.AddIndex(
            model_name='arranger',
            index=models.Index(fields=['last_name'], name='secondapp_a_last_na_4e27c5_idx'),
        ),
        migrations.AddIndex(
            model_name='arranger',
            index=models.Index(fields=['role'], name='secondapp_a_role_e7baf0_idx'),
        ),
        migrations.AddIndex(
            model_name='composer',
            index=models.Index(fields=['last_name'], name='secondapp_c_last_na_3c6b8d_idx'),
        ),
        migrations.AddIndex(
            model_name='composer',
            index=models.Index(fields=['role'], name='secondapp_c_role_78d0cc_idx'),
        ),
        migrations.AddIndex(
            model_name='musician',
            index=models.Index(fields=['last_name'], name='secondapp_m_last_na_cb38bd_idx'),
        ),
        migrations.AddIndex(
            model_name='musician',
            index=models.Index(fields=['role'], name='secondapp_m_role_e2bf44_idx'),
        ),
        migrations.AddIndex(
            model_name='poet',
            index=models.Index(fields=['last_name'], name='secondapp_p_last_na_9563bf_idx'),
        ),
        migrations.AddIndex(
            model_name='poet',
            index=models.Index(fields=['role'], name='secondapp_p_role_e0ba0a_idx'),
        ),
        migrations.AddIndex(
            model_name='rehearsal',
            index=models.Index(fields=['calendar'], name='secondapp_r_calenda_b23ac4_idx'),
        ),
        migrations.AddIndex(
            model_name='rehearsal',
            index=models.Index(fields=['is_cancelled'], name='secondapp_r_is_canc_d4c692_idx'),
        ),
        migrations.AddIndex(
            model_name='singer',
            index=models.Index(fields=['last_name'], name='secondapp_s_last_na_9e3075_idx'),
        ),
        migrations.AddIndex(
            model_name='singer',
            index=models.Index(fields=['role'], name='secondapp_s_role_254d1c_idx'),
        ),
        migrations.AddIndex(
            model_name='song',
            index=models.Index(fields=['title'], name='secondapp_s_title_50d975_idx'),
        ),
        migrations.AddIndex(
            model_name='song',
            index=models.Index(fields=['genre'], name='secondapp_s_genre_e8c0e9_idx'),
        ),
    ]
