# Generated by Django 5.2.5 on 2025-09-04 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secondapp', '0009_alter_arranger_options_alter_composer_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rehearsal',
            name='singers',
            field=models.ManyToManyField(blank=True, related_name='rehearsal_set', to='secondapp.singer'),
        ),
    ]
